buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.palantir.baseline-error-prone:gradle-baseline-error-prone:0.26.0'
        classpath 'com.palantir.gradle.failure-reports:gradle-failure-reports:1.21.0'
        classpath 'com.palantir.gradle.guide:gradle-guide:1.32.0'
        classpath 'com.palantir.gradle.idea-configuration:gradle-idea-configuration:0.11.0'
        classpath 'com.palantir.gradle.idea-language-injector:gradle-idea-language-injector:0.5.0'
        classpath 'com.palantir.gradle.jdks:gradle-jdks:0.82.0'
        classpath 'com.palantir.gradle.jdkslatest:gradle-jdks-latest:0.32.0'
        classpath 'com.palantir.gradle.plugintesting:gradle-plugin-testing:0.76.0'
        classpath 'com.palantir.jakartapackagealignment:jakarta-package-alignment:0.7.0'
        classpath 'com.palantir.gradle.externalpublish:gradle-external-publish-plugin:2.1.0'
        classpath 'com.palantir.javaformat:gradle-palantir-java-format:2.97.0'
        classpath 'com.palantir.suppressible-error-prone:gradle-suppressible-error-prone:2.33.0'
        classpath 'com.palantir.baseline:gradle-baseline-java:7.9.0'
    }
}

plugins {
    id 'com.gradle.plugin-publish' version '2.1.1'
    id 'com.palantir.git-version' version '4.0.0'
    id 'com.palantir.idea-test-fix' version '0.1.0'
    id 'com.palantir.baseline' version '7.9.0'
    id 'com.palantir.consistent-versions' version '3.19.0'
    id 'java-gradle-plugin'
    id 'groovy'
}
allprojects {
    apply plugin: 'com.palantir.jakarta-package-alignment'
}

apply plugin: 'com.palantir.baseline'
apply plugin: 'com.palantir.baseline-error-prone-root'
apply plugin: 'com.palantir.baseline-java-versions'
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'com.palantir.java-format'
apply plugin: 'com.palantir.jdks'
apply plugin: 'com.palantir.jdks.latest'
apply plugin: 'com.palantir.failure-reports'
apply plugin: 'com.palantir.gradle-guide'
apply plugin: 'com.palantir.gradle-plugin-testing'
apply plugin: 'com.palantir.idea-language-injector'

group 'com.palantir.gradle.gitversion'
version System.env.CIRCLE_TAG ?: gitVersion()

repositories {
    mavenCentral() { metadataSources { mavenPom(); ignoreGradleMetadataRedirection() } }
}

dependencies {
    implementation gradleApi()
    implementation 'com.google.guava:guava'
    implementation 'com.palantir.gradle.utils:environment-variables'
    implementation 'com.palantir.gradle.utils:exec'
    implementation 'com.github.ben-manes.caffeine:caffeine'

    annotationProcessor 'org.immutables:value'
    compileOnly 'org.immutables:value::annotations'

    testImplementation gradleTestKit()
    testImplementation 'com.netflix.nebula:nebula-test'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'one.util:streamex'

    testImplementation('org.spockframework:spock-core') {
        exclude module: 'groovy-all'
    }
    testRuntimeOnly 'junit:junit'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile) {
    options.compilerArgs += ['-Werror']
}

gradlePlugin {
    website = 'https://github.com/palantir/gradle-git-version'
    vcsUrl = 'https://github.com/palantir/gradle-git-version'

    plugins {
        gitVersionPlugin {
            id = 'com.palantir.git-version'
            displayName = 'Palantir Gradle Git-Version'
            implementationClass = 'com.palantir.gradle.gitversion.GitVersionPlugin'
            description = 'Gradle Git-Version is a plugin that generates a version for use with Gradle by calling git-describe.'
            tags.set(['git', 'version'])
        }
    }
}

// Configure the publishPlugins task
publishPlugins.onlyIf { System.env.CIRCLE_TAG }
tasks.publish.dependsOn publishPlugins
project.ext.'gradle.publish.key' = System.env["GRADLE_KEY"]
project.ext.'gradle.publish.secret' = System.env["GRADLE_SECRET"]

javaVersions {
    javaCompiler = 25
    libraryTarget = 17
}

jdks {
    daemonTarget = 21
}

gradleTestUtils {
    configurationCacheEnabled = true
}
