buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.palantir.gradle.failure-reports:gradle-failure-reports:1.16.0'
        classpath 'com.palantir.gradle.guide:gradle-guide:1.13.0'
        classpath 'com.palantir.gradle.idea-configuration:gradle-idea-configuration:0.6.0'
        classpath 'com.palantir.gradle.jdks:gradle-jdks:0.69.0'
        classpath 'com.palantir.gradle.jdkslatest:gradle-jdks-latest:0.22.0'
        classpath 'com.palantir.gradle.plugintesting:gradle-plugin-testing:0.13.0'
        classpath 'com.palantir.jakartapackagealignment:jakarta-package-alignment:0.6.0'
        classpath 'com.palantir.gradle.externalpublish:gradle-external-publish-plugin:1.25.0'
        classpath 'com.palantir.javaformat:gradle-palantir-java-format:2.81.0'
        classpath 'com.palantir.suppressible-error-prone:gradle-suppressible-error-prone:2.22.0'
        classpath 'com.palantir.baseline:gradle-baseline-java:6.65.0'
    }
}

plugins {
    id 'com.gradle.plugin-publish' version '2.0.0'
    id 'com.palantir.git-version' version '4.0.0'
    id 'com.palantir.idea-test-fix' version '0.1.0'
    id 'com.palantir.baseline' version '6.65.0'
    id 'com.palantir.consistent-versions' version '3.2.0'
    id 'java-gradle-plugin'
    id 'groovy'
}
allprojects {
    apply plugin: 'com.palantir.jakarta-package-alignment'
}

apply plugin: 'com.palantir.baseline'
apply plugin: 'com.palantir.baseline-java-versions'
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'com.palantir.java-format'
apply plugin: 'com.palantir.jdks'
apply plugin: 'com.palantir.jdks.latest'
apply plugin: 'com.palantir.failure-reports'
apply plugin: 'com.palantir.gradle-guide'
apply plugin: 'com.palantir.gradle-plugin-testing'

group 'com.palantir.gradle.gitversion'
version System.env.CIRCLE_TAG ?: gitVersion()

repositories {
    mavenCentral() { metadataSources { mavenPom(); ignoreGradleMetadataRedirection() } }
}

dependencies {
    implementation gradleApi()
    implementation 'com.google.guava:guava'

    annotationProcessor 'org.immutables:value'
    compileOnly 'org.immutables:value::annotations'

    testImplementation gradleTestKit()
    testImplementation 'com.netflix.nebula:nebula-test'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    testImplementation('org.spockframework:spock-core') {
        exclude module: 'groovy-all'
    }
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile) {
    options.compilerArgs += ['-Werror']
}

gradlePlugin {
    website = 'https://github.com/palantir/gradle-git-version'
    vcsUrl = 'https://github.com/palantir/gradle-git-version'

    plugins {
        gitVersionPlugin {
            id = 'com.palantir.git-version'
            displayName = 'Palantir Gradle Git-Version'
            implementationClass = 'com.palantir.gradle.gitversion.GitVersionPlugin'
            description = 'Gradle Git-Version is a plugin that generates a version for use with Gradle by calling git-describe.'
            tags.set(['git', 'version'])
        }
    }
}

// Configure the publishPlugins task
publishPlugins.onlyIf { System.env.CIRCLE_TAG }
tasks.publish.dependsOn publishPlugins
project.ext.'gradle.publish.key' = System.env["GRADLE_KEY"]
project.ext.'gradle.publish.secret' = System.env["GRADLE_SECRET"]

javaVersions {
    libraryTarget = 17
}

jdks {
    daemonTarget = 21
}

gradleTestUtils {
    gradleVersions = ['8.14.3']
}
