com.google.guava:guava = 33.6.0-jre
com.palantir.gradle.plugintesting:gradle-plugin-testing-junit = 0.68.0
org.assertj:assertj-core = 3.27.7
org.immutables:* = 2.12.1
org.junit.jupiter:* = 6.0.3
org.junit.platform:* = 6.0.3
org.spockframework:spock-core = 2.1-groovy-3.0
com.netflix.nebula:nebula-test = 11.11.3
com.palantir.gradle.utils:environment-variables = 0.23.0
com.palantir.gradle.utils:exec = 0.24.0
com.github.ben-manes.caffeine:caffeine = 3.2.3
one.util:streamex = 0.8.4
